import { test } from "node:test";
import assert from "node:assert/strict";
import {
  selectCitedSources,
  buildReferenceLines,
  countDailySources,
} from "../src/sections/ai-news.mjs";

// ---------------------------------------------------------------------------
// 2026-09-27 review B1: the reference list was FILTERED but still rendered by
// position.
//
//   const citedSources = [...citedIndices].sort().map((i) => sources[i]);
//   const refLines = citedSources.map(s => ...)
//
// The `[N]` markers in the body index the FULL source list. Once the list was
// filtered down to the cited subset, the renderer emitted them 1..N again, so a
// body citing [1] and [6] produced a two-line reference list whose line 2 was
// printed as the wrong number by anyone reading the markdown — and the poster,
// which consumes `posterSources` positionally, put the wrong headline against
// the citation too. This was live in the shipped 2026-09-27 note.
//
// The numbering must be carried by the SELECTION, not regenerated by the
// renderer.
// ---------------------------------------------------------------------------

test("selectCitedSources: keeps each source's ORIGINAL 1-based citation number", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
    { title: "C", url: "https://c.test/3" },
    { title: "D", url: "https://d.test/4" },
    { title: "E", url: "https://e.test/5" },
    { title: "F", url: "https://f.test/6" },
  ];
  const selected = selectCitedSources(sources, "见 [6] 与 [1]。");
  assert.deepEqual(
    selected.map((c) => c.n),
    [1, 6],
    "numbers must be the body's own, not 1..2",
  );
  assert.deepEqual(
    selected.map((c) => c.source.title),
    ["A", "F"],
  );
});

test("selectCitedSources: an out-of-range marker is ignored, not clamped", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
  ];
  const selected = selectCitedSources(sources, "引用 [1] [2] [9] [0]");
  assert.deepEqual(selected.map((c) => c.n), [1, 2]);
});

test("selectCitedSources: no markers -> every source, numbered by position", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
  ];
  const selected = selectCitedSources(sources, "正文没有任何引用标记");
  assert.deepEqual(selected.map((c) => c.n), [1, 2]);
});

test("buildReferenceLines: a body citing [6] against a 5-entry list does not renumber", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
    { title: "C", url: "https://c.test/3" },
    { title: "D", url: "https://d.test/4" },
    { title: "E", url: "https://e.test/5" },
  ];
  const selected = selectCitedSources(sources, "结论 [4] 与 [1]");
  const lines = buildReferenceLines(selected, { stripMarkdown: (t) => t, sanitizeUrl: (u) => u });
  assert.equal(lines.length, 2);
  assert.match(lines[0], /A/);
  assert.match(lines[1], /D/, "the second line must be the [4] source, not B");
});

test("buildReferenceLines: still degrades a non-http(s) URL to a plain title", () => {
  const selected = selectCitedSources(
    [{ title: "Evil [x](y)", url: "javascript:alert(1)" }],
    "见 [1]",
  );
  const lines = buildReferenceLines(selected, {
    stripMarkdown: (t) => t,
    sanitizeUrl: () => null,
  });
  // 2026-09-28 G1: expected string gained the `[1]` prefix. The assertion's
  // SUBJECT is unchanged — a non-http(s) scheme must not become a clickable
  // link, and the brackets in the title must still be escaped so they cannot
  // form a link either. Only the number the renderer now prints differs; the
  // escaping itself (`Evil \[x\]\(y\)`) is asserted exactly as before.
  assert.equal(
    lines[0],
    "- [1] Evil \\[x\\]\\(y\\)",
    "no clickable link for a non-http(s) scheme, number still shown",
  );
});

// ---------------------------------------------------------------------------
// 2026-09-27 review B2: 当日素材 was undercounted to zero.
//
// `fromDaily` was stamped ONLY on the hard-source list (HN/36kr/arXiv), so a
// day whose hard sources all failed but which had a dozen same-day linux.do
// posts reported "当日素材 0 条" and printed the 低素材 warning — the report
// describing itself as stale while resting entirely on material published that
// morning. That is the warning that exists to make the user distrust the body.
//
// Provenance is decided by RECENCY here, not by which collector happened to
// produce the card: a forum post created this morning is same-day material.
// ---------------------------------------------------------------------------

const BJ = (s) => ({ publishedAt: Date.parse(`${s}T04:00:00Z`) });

test("countDailySources: a same-day forum post counts as 当日素材", () => {
  const n = countDailySources(
    [
      { title: "今日发布", url: "https://linux.do/t/1", ...BJ("2026-09-27") },
      { title: "旧闻", url: "https://linux.do/t/2", ...BJ("2026-09-20") },
      { title: "无时间戳", url: "https://linux.do/t/3" },
    ],
    "2026-09-27",
  );
  assert.equal(n, 1, "only the same-day card counts");
});

test("countDailySources: the hard-source fromDaily flag still counts", () => {
  const n = countDailySources(
    [
      { title: "硬源", url: "https://hn/1", fromDaily: true },
      { title: "论坛旧闻", url: "https://linux.do/t/2", ...BJ("2026-09-20") },
    ],
    "2026-09-27",
  );
  assert.equal(n, 1);
});

test("countDailySources: a timestamp-less card is NOT silently same-day", () => {
  // Contrasts with the test above: a Tavily/firecrawl card has no timestamp, so
  // nothing about it is provably same-day. Counting it would inflate the
  // material count with unknowns and suppress the low-material warning that
  // protects the reader on a genuinely thin day.
  const n = countDailySources([{ title: "无时间戳", url: "https://x/1" }], "2026-09-27");
  assert.equal(n, 0);
});

test("countDailySources: the grace window is respected, as filterByRecency applies it", () => {
  // arXiv papers carry recencyGraceDays: 1 — a card that passed the recency gate
  // on the strength of its grace must still count, otherwise the two functions
  // disagree about the same card.
  const n = countDailySources(
    [
      { title: "arXiv 昨日", url: "https://arxiv/1", ...BJ("2026-09-26"), recencyGraceDays: 1 },
      { title: "arXiv 前日", url: "https://arxiv/2", ...BJ("2026-09-24"), recencyGraceDays: 1 },
    ],
    "2026-09-27",
  );
  assert.equal(n, 1, "the card inside the grace window counts");
});

// ---------------------------------------------------------------------------
// 2026-09-28 review G1: B1 fixed the SELECTION but not the RENDER.
//
//   selectCitedSources returns {n, source}; buildReferenceLines then did
//     return `- [${title}](<${url}>)`     // <- n destructured away, never printed
//
// The reference bullets are unnumbered by design (verified unchanged on
// 2026-09-25/26/27), so a reader resolves a body's `[N]` by COUNTING the
// displayed entries. That is only correct when the cited subset happens to be
// 1..k contiguous. The moment a body skips a marker, every number shifts.
//
// Shipped 2026-09-28: AI.md cited [2]..[10] and listed 9 unnumbered bullets.
// [3] (Cloudflare Turnstile) resolved to the 2nd line, 龙猫加入opencode; [10]
// resolved to nothing at all. Every one of the 9 markers was wrong.
//
// The number is already in the data. The renderer only has to print it.
// ---------------------------------------------------------------------------

const DEPS = { stripMarkdown: (t) => t, sanitizeUrl: (u) => u };
const FIVE = [
  { title: "A", url: "https://a.test/1" },
  { title: "B", url: "https://b.test/2" },
  { title: "C", url: "https://c.test/3" },
  { title: "D", url: "https://d.test/4" },
  { title: "E", url: "https://e.test/5" },
];

test("G1: a body skipping markers must still render each source under its OWN number", () => {
  // The shipped shape: cites 2, 3, 5 — skips 1 and 4.
  const lines = buildReferenceLines(selectCitedSources(FIVE, "一 [2] 二 [3] 三 [5]"), DEPS);
  assert.equal(lines.length, 3);
  assert.match(lines[0], /^\- \[2\] /, "line 1 is source B and must PRINT [2], not sit unnumbered");
  assert.match(lines[1], /^\- \[3\] /, "line 2 is source C and must PRINT [3]");
  assert.match(lines[2], /^\- \[5\] /, "line 3 is source E and must PRINT [5]");
});

test("G1: a reader counting the list must land on the cited source", () => {
  // The actual failure: body says [3] is Cloudflare; counting the bullets must
  // not hand the reader 龙猫. Assert the number the reader SEES maps to the
  // source the body named.
  const lines = buildReferenceLines(selectCitedSources(FIVE, "Turnstile [3]"), DEPS);
  assert.equal(lines.length, 1);
  assert.match(lines[0], /^\- \[3\] \[C\]/, "the only bullet must be [3] C — visible number, not position");
});

test("G1: a contiguous subset is unchanged (1..k still prints 1..k)", () => {
  const lines = buildReferenceLines(selectCitedSources(FIVE, "一 [1] 二 [2]"), DEPS);
  assert.match(lines[0], /^\- \[1\] /);
  assert.match(lines[1], /^\- \[2\] /);
});

test("G1: the no-marker path numbers every source by position", () => {
  // With no [N] in the body selectCitedSources returns 1..N, so printing n is
  // identical to printing position. Guards the degraded/fallback path.
  const lines = buildReferenceLines(selectCitedSources(FIVE, "正文没有任何引用标记"), DEPS);
  assert.equal(lines.length, 5);
  lines.forEach((l, i) => assert.match(l, new RegExp(`^\\- \\[${i + 1}\\] `)));
});

test("G1: the non-http(s) degrade path keeps the number and drops the link", () => {
  const lines = buildReferenceLines(selectCitedSources(FIVE, "见 [2]"), {
    stripMarkdown: (t) => t,
    sanitizeUrl: () => null,
  });
  assert.equal(lines[0], "- [2] B", "number survives even when the URL is rejected");
});

test("G1: an entry with no n falls back to its position, never printing [undefined]", () => {
  const lines = buildReferenceLines([{ source: { title: "X", url: "https://x.test/9" } }], DEPS);
  assert.equal(lines[0], "- [1] [X](<https://x.test/9>)");
});

// ---------------------------------------------------------------------------
// 2026-09-28 review H1: a COMBINED citation resolved to nothing.
//
// The parser matched /\[(\d+)\]/ — one number, immediately closed by "]". A
// body that cites several sources at once writes "[22, 25]", and that string
// does not match the pattern at all: the scan consumes "[22" and dies on the
// comma, so NEITHER 22 nor 25 is recorded.
//
//   Shipped AI-周报.md, 2026-09-25: body carried one combined marker,
//   "[22, 25]". The reference list held 1 2 4 6 9 13 16 17 19 21 24 26 27
//   29 30. 22 and 25 appear nowhere in it — two assertions in the delivered
//   note pointed at no source at all, and did so silently: the note still
//   rendered, still looked complete, and simply under-reported by two.
//
// This is the worst failure shape in the whole pipeline because it is
// invisible. A missing source in the list is indistinguishable from a body that
// chose not to cite anything, unless you go and count the markers.
// ---------------------------------------------------------------------------

const THIRTY = Array.from({ length: 30 }, (_, i) => ({
  title: `S${i + 1}`,
  url: `https://s.test/${i + 1}`,
}));

test("H1: a combined marker [22, 25] resolves to BOTH sources", () => {
  const selected = selectCitedSources(THIRTY, "两条并列的说法 [22, 25]");
  assert.deepEqual(
    selected.map((c) => c.n),
    [22, 25],
    "both halves of the marker must reach the reference list",
  );
  assert.deepEqual(
    selected.map((c) => c.source.title),
    ["S22", "S25"],
  );
});

test("H1: the shipped 2026-09-25 shape leaves NO marker unresolved", () => {
  // The end-to-end shape, not the regex: 15 single markers plus one combined
  // one, against 30 sources. Before the fix this returned 15 entries and the
  // two numbers in the combined marker were silently absent from the output.
  const body = Array.from({ length: 15 }, (_, i) => `[${i * 2 + 1}]`).join(" ") + " 合并 [22, 25]";
  const selected = selectCitedSources(THIRTY, body);
  const numbers = selected.map((c) => c.n);
  for (const cited of [22, 25]) {
    assert.ok(numbers.includes(cited), `cited [${cited}] must appear in the reference list`);
  }
});

test("H1: a combined marker survives into the rendered reference lines", () => {
  const lines = buildReferenceLines(selectCitedSources(THIRTY, "并列 [22, 25]"), DEPS);
  assert.equal(lines.length, 2);
  assert.match(lines[0], /^\- \[22\] /, "line 1 must print [22], not sit unnumbered");
  assert.match(lines[1], /^\- \[25\] /, "line 2 must print [25]");
});

test("H1: a combined marker's halves obey the same range guard as a single one", () => {
  // The fix must widen the SHAPE, not the trust: an out-of-range or malformed
  // half is still ignored rather than clamped onto a real source.
  const selected = selectCitedSources(FIVE, "越界 [2, 99]，非数字 [2, abc]，负数 [-1, 2]");
  assert.deepEqual(selected.map((c) => c.n), [2], "only the in-range, well-formed half survives");
});

test("H1: a single marker is unchanged by the widened parser", () => {
  // The parser now accepts an optional comma-separated tail. That must not
  // change the single-marker case at all — the overwhelmingly common one.
  assert.deepEqual(selectCitedSources(FIVE, "一 [1] 二 [3]").map((c) => c.n), [1, 3]);
});

test("H1: a bracket that is not a citation is still not a citation", () => {
  // The body legitimately contains markdown links and bracketed non-numbers.
  // Widening must not start harvesting digits out of them.
  const selected = selectCitedSources(FIVE, "见 [链接](https://x.test) 与 [注] 以及 [3]");
  assert.deepEqual(selected.map((c) => c.n), [3]);
});
