import { test } from "node:test";
import assert from "node:assert/strict";
import { selectCitedSources, buildReferenceLines } from "../src/sections/ai-news.mjs";

// ---------------------------------------------------------------------------
// 2026-09-27 review B1: the reference list was FILTERED but still rendered by
// position.
//
//   const citedSources = [...citedIndices].sort().map((i) => sources[i]);
//   const refLines = citedSources.map(s => ...)
//
// The `[N]` markers in the body index the FULL source list. Once the list was
// filtered down to the cited subset, the renderer emitted them 1..N again, so a
// body citing [1] and [6] produced a two-line reference list whose line 2 was
// printed as the wrong number by anyone reading the markdown — and the poster,
// which consumes `posterSources` positionally, put the wrong headline against
// the citation too. This was live in the shipped 2026-09-27 note.
//
// The numbering must be carried by the SELECTION, not regenerated by the
// renderer.
// ---------------------------------------------------------------------------

test("selectCitedSources: keeps each source's ORIGINAL 1-based citation number", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
    { title: "C", url: "https://c.test/3" },
    { title: "D", url: "https://d.test/4" },
    { title: "E", url: "https://e.test/5" },
    { title: "F", url: "https://f.test/6" },
  ];
  const selected = selectCitedSources(sources, "见 [6] 与 [1]。");
  assert.deepEqual(
    selected.map((c) => c.n),
    [1, 6],
    "numbers must be the body's own, not 1..2",
  );
  assert.deepEqual(
    selected.map((c) => c.source.title),
    ["A", "F"],
  );
});

test("selectCitedSources: an out-of-range marker is ignored, not clamped", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
  ];
  const selected = selectCitedSources(sources, "引用 [1] [2] [9] [0]");
  assert.deepEqual(selected.map((c) => c.n), [1, 2]);
});

test("selectCitedSources: no markers -> every source, numbered by position", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
  ];
  const selected = selectCitedSources(sources, "正文没有任何引用标记");
  assert.deepEqual(selected.map((c) => c.n), [1, 2]);
});

test("buildReferenceLines: a body citing [6] against a 5-entry list does not renumber", () => {
  const sources = [
    { title: "A", url: "https://a.test/1" },
    { title: "B", url: "https://b.test/2" },
    { title: "C", url: "https://c.test/3" },
    { title: "D", url: "https://d.test/4" },
    { title: "E", url: "https://e.test/5" },
  ];
  const selected = selectCitedSources(sources, "结论 [4] 与 [1]");
  const lines = buildReferenceLines(selected, { stripMarkdown: (t) => t, sanitizeUrl: (u) => u });
  assert.equal(lines.length, 2);
  assert.match(lines[0], /A/);
  assert.match(lines[1], /D/, "the second line must be the [4] source, not B");
});

test("buildReferenceLines: still degrades a non-http(s) URL to a plain title", () => {
  const selected = selectCitedSources(
    [{ title: "Evil [x](y)", url: "javascript:alert(1)" }],
    "见 [1]",
  );
  const lines = buildReferenceLines(selected, {
    stripMarkdown: (t) => t,
    sanitizeUrl: () => null,
  });
  assert.equal(lines[0], "- Evil \\[x\\]\\(y\\)", "no clickable link for a non-http(s) scheme");
});
