import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Regression net for template/disk drift between the wrapper generated by
// scripts/install-launchd.mjs and the generated artifact on disk
// (scripts/run-daily-wrapper.sh). The wrapper is what launchd runs at 09:00 —
// a hand-edited wrapper or an unregenerated template silently changes what the
// daily job executes, so the two are diffed here on every test run.
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WRAPPER = path.join(ROOT, "scripts", "run-daily-wrapper.sh");
const INSTALLER = path.join(ROOT, "scripts", "install-launchd.mjs");

test("run-daily-wrapper.sh: passes bash -n syntax check", () => {
  const res = spawnSync("/bin/bash", ["-n", WRAPPER], { encoding: "utf8" });
  assert.equal(res.status, 0, `bash -n failed: ${res.stderr}`);
});

test("run-daily-wrapper.sh: brew-first candidate and exit 127 fallback, no pinned Cellar dir", () => {
  const sh = fs.readFileSync(WRAPPER, "utf8");
  assert.ok(sh.includes("/opt/homebrew/bin/node"), "brew arm64 node candidate present");
  assert.match(sh, /exit 127/, "no-node fallback still exits 127 into err.log");
  // A pinned Cellar/node/<version> binary dies on dyld after brew upgrades
  // (2026-09-19~21 incident) — no CANDIDATE may point into a versioned Cellar
  // dir. (The Chinese comment mentioning "Cellar/node/<版本>" is prose, not a
  // path, so the check is scoped to the candidate line.)
  const candidateLine = sh.match(/^for NODE_BIN in (.+); do$/m)?.[1] || "";
  assert.ok(candidateLine, "wrapper contains the NODE_BIN candidate for-loop");
  assert.doesNotMatch(candidateLine, /Cellar\/node\//, "no version-pinned Cellar candidate");
});

test("run-daily-wrapper.sh: for-loop candidates match the installer template (drift guard)", () => {
  const sh = fs.readFileSync(WRAPPER, "utf8");
  const src = fs.readFileSync(INSTALLER, "utf8");
  const wrapLine = sh.match(/^for NODE_BIN in (.+); do$/m)?.[1];
  assert.ok(wrapLine, "wrapper contains the NODE_BIN candidate for-loop");
  const tplLine = src.match(/^  "for NODE_BIN in (.+?); do";$/m)?.[1];
  assert.ok(tplLine, "installer contains the candidate-line template literal");

  // The template carries __RESOLVED_NODE__ where install-time discovery inserts
  // the observed node binary (the slot is dropped when discovery found nothing).
  const tplTokens = tplLine.split(" ");
  const wrapTokens = wrapLine.split(" ");
  const statics = tplTokens.filter((t) => t !== "__RESOLVED_NODE__");
  const at = tplTokens.indexOf("__RESOLVED_NODE__");
  if (wrapTokens.length === statics.length) {
    // No discovered fallback slot on disk — the remaining tokens must equal the
    // static candidates in template order.
    assert.deepEqual(wrapTokens, statics);
  } else {
    assert.equal(wrapTokens.length, statics.length + 1, "exactly one discovered node path in the fallback slot");
    assert.deepEqual(wrapTokens.slice(0, at), statics.slice(0, at), "static candidates before the slot");
    assert.match(wrapTokens[at], /^\//, "discovered candidate is an absolute path");
    assert.deepEqual(wrapTokens.slice(at + 1), statics.slice(at), "static candidates after the slot");
  }
});
