#!/usr/bin/env node
// install-launchd.mjs — register a launchd LaunchAgent that runs the daily report
// automatically (Phase 3 of the DallyReport 优化开发文档).
//
// Design (mirrors DailyBrief's proven install.mjs):
//   - Creates ~/Library/LaunchAgents/com.mango.dallyreport.plist
//   - Runs at StartCalendarInterval 09:00 local time (Beijing-labeled report date
//     is computed by run.mjs itself via beijingDateFor, so host TZ doesn't matter).
//   - Logs stdout/stderr to <project>/logs/launchd.{out,err}.log
//   - Uninstall: node scripts/uninstall-launchd.mjs
//
// Idempotent + safe:
//   - A job that is actually LOADED is booted out before the plist is replaced
//     (the old code wrote the plist first, so its existsSync guard was always
//     true and the "unload" ran against the freshly written file).
//   - Wrapper resolves node at RUNTIME from fixed candidate paths (brew/system),
//     plus the node binary observed at install time appended as a fallback
//     candidate — never pinned as the first choice: brew upgrades swap
//     Cellar/node/<ver> dirs and a pinned binary dies on dyld (2026-09-19~21:
//     ada-url 3->4 removed libada.3.dylib, pinned node 26.0.0 crashed 3 days
//     before anyone looked).
//   - Never edits ~/.env, never touches the cron table.
//
// Requires: macOS. On Linux/Windows print a hint and exit 1.

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

if (process.platform !== "darwin") {
  console.error("launchd 仅支持 macOS（本机即 Mac）。Linux 可用 cron，Windows 用任务计划程序。");
  process.exit(1);
}

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const LABEL = "com.mango.dallyreport";
const WRAPPER = path.join(PROJECT_ROOT, "scripts", "run-daily-wrapper.sh");
const PLIST = path.join(os.homedir(), "Library", "LaunchAgents", `${LABEL}.plist`);
const LOG_DIR = path.join(PROJECT_ROOT, "logs");

// The wrapper's node-candidate for-loop, kept as a single literal line so
// test/launchd-wrapper.test.mjs can diff it against the generated wrapper and
// fail on template/disk drift. __RESOLVED_NODE__ is replaced with the node
// binary discovered at install time (dropped when discovery finds nothing) —
// brew paths first, the discovered path as fallback before /usr/bin/node.
const NODE_CANDIDATE_LINE_TPL =
  "for NODE_BIN in /opt/homebrew/bin/node /usr/local/bin/node __RESOLVED_NODE__ /usr/bin/node; do";

// `command -v node` is a shell builtin — run it via a login bash so PATH matches
// an interactive session. Only trust absolute, executable paths (a bare word
// would be a shell function/alias, not a binary).
function discoverNode() {
  const res = spawnSync("/bin/bash", ["-lc", "command -v node"], { encoding: "utf8" });
  const p = res.stdout?.trim() || "";
  if (!p || !p.startsWith("/")) return "";
  try {
    fs.accessSync(p, fs.constants.X_OK);
    return p;
  } catch {
    return "";
  }
}

function buildCandidateLine(resolvedNode) {
  if (resolvedNode) return NODE_CANDIDATE_LINE_TPL.replace("__RESOLVED_NODE__", resolvedNode);
  return NODE_CANDIDATE_LINE_TPL.replace("__RESOLVED_NODE__ ", "");
}

// Write the shell wrapper that cd's into the project and runs `node src/run.mjs`.
// A shell wrapper (instead of ProgramArguments pointing straight at run.mjs) keeps
// the working directory correct without relying on launchd's working dir support.
function writeWrapper() {
  fs.mkdirSync(path.dirname(WRAPPER), { recursive: true });
  const candidateLine = buildCandidateLine(discoverNode());
  const triedList = candidateLine.replace(/^for NODE_BIN in /, "").replace(/; do$/, "");
  const sh = `#!/bin/bash
# Generated by scripts/install-launchd.mjs — do not edit by hand.
cd "${PROJECT_ROOT}" || exit 1
# launchd 的 PATH 只有 /usr/bin:/bin，且 brew 升级会更换 Cellar/node/<版本> 目录——
# 禁止钉死安装时的 node 路径，运行时按候选位解析；全部落空则报错退出（127）进 err.log。
${candidateLine}
  [ -x "$NODE_BIN" ] && exec "$NODE_BIN" src/run.mjs
done
echo "$(date '+%Y-%m-%d %H:%M:%S') run-daily-wrapper: no usable node found (tried ${triedList})" >&2
exit 127
`;
  fs.writeFileSync(WRAPPER, sh, { mode: 0o755 });
}

function writePlist() {
  fs.mkdirSync(LOG_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(PLIST), { recursive: true });
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${WRAPPER}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>9</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/launchd.out.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/launchd.err.log</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
`;
  fs.writeFileSync(PLIST, plist, "utf8");
}

function launchctl(...args) {
  const res = spawnSync("launchctl", args, { stdio: "inherit" });
  if (res.status !== 0) throw new Error(`launchctl ${args.join(" ")} failed (${res.status})`);
}

// True only when the job is actually loaded in this user's launchd domain.
function isJobLoaded() {
  const res = spawnSync("launchctl", ["print", `gui/${os.userInfo().uid}/${LABEL}`], { stdio: "ignore" });
  return res.status === 0;
}

// Boot out the loaded job; fall back to the legacy `unload` on older macOS.
// Returns the command that worked, or null if both failed.
function unloadLoadedJob() {
  const bootout = spawnSync("launchctl", ["bootout", `gui/${os.userInfo().uid}/${LABEL}`], { stdio: "ignore" });
  if (bootout.status === 0) return "bootout";
  const unload = spawnSync("launchctl", ["unload", PLIST], { stdio: "ignore" });
  if (unload.status === 0) return "unload";
  return null;
}

try {
  writeWrapper();
  console.log(`[1/4] wrapper 写好: ${WRAPPER}`);

  // Unload the previous registration ONLY if the job is actually loaded. The
  // old flow wrote the plist first, so its `fs.existsSync(PLIST)` guard was
  // always true and `launchctl unload` ran against the fresh file.
  const plistExisted = fs.existsSync(PLIST);
  if (isJobLoaded()) {
    const how = unloadLoadedJob();
    if (!how) {
      throw new Error(
        `无法卸载已加载的任务，请手动执行: launchctl bootout gui/${os.userInfo().uid}/${LABEL}`,
      );
    }
    console.log(`[2/4] 旧任务已卸载（launchctl ${how}）`);
  } else {
    console.log(plistExisted ? "[2/4] plist 已存在但任务未加载，直接覆盖。" : "[2/4] 首次安装，无需卸载。");
  }

  writePlist();
  console.log(`[3/4] plist 写好: ${PLIST}`);

  console.log("[4/4] launchctl load …");
  launchctl("load", PLIST);

  console.log(`已注册 launchd 定时任务:`);
  console.log(`  label: ${LABEL}`);
  console.log(`  触发:  每天 09:00（本地时区）`);
  console.log(`  日志:  ${LOG_DIR}/launchd.{out,err}.log`);
  console.log(`  卸载:  node scripts/uninstall-launchd.mjs`);
  // Note: macOS may sleep through the scheduled time; use pmset wake schedule if
  // you need wake-on-schedule.
  console.log(`  提示:  macOS 睡眠时 launchd 会跳过本次；需定时唤醒请配 pmset wake schedule。`);
  console.log(`  手动触发验证: launchctl start ${LABEL}`);
} catch (err) {
  console.error(`✖ 安装失败: ${err.message}`);
  process.exit(1);
}