#!/usr/bin/env node
// install-launchd.mjs — register a launchd LaunchAgent that runs the daily report
// automatically (Phase 3 of the DallyReport 优化开发文档).
//
// Design (mirrors DailyBrief's proven install.mjs):
//   - Creates ~/Library/LaunchAgents/com.mango.dallyreport.plist
//   - Runs at StartCalendarInterval 09:00 local time (Beijing-labeled report date
//     is computed by run.mjs itself via beijingDateFor, so host TZ doesn't matter).
//   - Logs stdout/stderr to <project>/logs/launchd.{out,err}.log
//   - Uninstall: node scripts/uninstall-launchd.mjs
//
// Idempotent + safe:
//   - Existing plist is unloaded+replaced (launchctl unload then load).
//   - Uses the same node binary that runs this script (process.execPath), not a
//     hardcoded path — survives Node version managers.
//   - Never edits ~/.env, never touches the cron table.
//
// Requires: macOS. On Linux/Windows print a hint and exit 1.

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

if (process.platform !== "darwin") {
  console.error("launchd 仅支持 macOS（本机即 Mac）。Linux 可用 cron，Windows 用任务计划程序。");
  process.exit(1);
}

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const LABEL = "com.mango.dallyreport";
const WRAPPER = path.join(PROJECT_ROOT, "scripts", "run-daily-wrapper.sh");
const PLIST = path.join(os.homedir(), "Library", "LaunchAgents", `${LABEL}.plist`);
const LOG_DIR = path.join(PROJECT_ROOT, "logs");

// Write the shell wrapper that cd's into the project and runs `node src/run.mjs`.
// A shell wrapper (instead of ProgramArguments pointing straight at run.mjs) keeps
// the working directory correct without relying on launchd's working dir support.
function writeWrapper() {
  fs.mkdirSync(path.dirname(WRAPPER), { recursive: true });
  const sh = `#!/bin/bash
# Generated by scripts/install-launchd.mjs — do not edit by hand.
cd "${PROJECT_ROOT}" || exit 1
exec "${process.execPath}" src/run.mjs
`;
  fs.writeFileSync(WRAPPER, sh, { mode: 0o755 });
}

function writePlist() {
  fs.mkdirSync(LOG_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(PLIST), { recursive: true });
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${WRAPPER}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>9</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/launchd.out.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/launchd.err.log</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
`;
  fs.writeFileSync(PLIST, plist, "utf8");
}

function launchctl(...args) {
  const res = spawnSync("launchctl", args, { stdio: "inherit" });
  if (res.status !== 0) throw new Error(`launchctl ${args.join(" ")} failed (${res.status})`);
}

try {
  writeWrapper();
  writePlist();
  console.log(`[1/3] wrapper + plist 写好: ${WRAPPER}`);
  console.log(`       plist: ${PLIST}`);

  // Unload previous registration (if any) before loading — idempotent.
  if (fs.existsSync(PLIST)) {
    try {
      spawnSync("launchctl", ["unload", PLIST], { stdio: "ignore" });
    } catch {
      /* first install — nothing to unload */
    }
  }
  console.log("[2/3] launchctl load …");
  launchctl("load", PLIST);

  console.log("[3/3] 已注册 launchd 定时任务:");
  console.log(`  label: ${LABEL}`);
  console.log(`  触发:  每天 09:00（本地时区）`);
  console.log(`  日志:  ${LOG_DIR}/launchd.{out,err}.log`);
  console.log(`  卸载:  node scripts/uninstall-launchd.mjs`);
  // Note: macOS may sleep through the scheduled time; use pmset wake schedule if
  // you need wake-on-schedule.
  console.log(`  提示:  macOS 睡眠时 launchd 会跳过本次；需定时唤醒请配 pmset wake schedule。`);
  console.log(`  手动触发验证: launchctl start ${LABEL}`);
} catch (err) {
  console.error(`✖ 安装失败: ${err.message}`);
  process.exit(1);
}