#!/bin/bash
# Generated by scripts/install-launchd.mjs — do not edit by hand.
cd "/Users/mango/project/claude-project/DallyReport" || exit 1
exec "/opt/homebrew/Cellar/node/26.0.0/bin/node" src/run.mjs
